services:
  bg-remove:
    build: .
    container_name: bg-remove
    ports:
      - "5173:5173"  # Host:Container port mapping
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0  # Explicit host declaration
    restart: unless-stopped # Auto-restart on failure
    volumes:
      - ./:/app
      - /app/node_modules

